STRATAGEMS_BY_DEPARTMENT = {
    "Patriotic Administration Center": {
        "MG-43 Machine Gun": ["down", "left", "down", "up", "right"],
        "APW-1 Anti-Materiel Rifle": ["down", "left", "right", "up", "down"],
        "M-105 Stalwart": ["down", "left", "down", "up", "up", "left"],
        "EAT-17 Expendable Anti-Tank": ["down", "down", "left", "up", "right"],
        "GR-8 Recoilless Rifle": ["down", "left", "right", "right", "left"],
        "FLAM-40 Flamethrower": ["down", "left", "up", "down", "up"],
        "AC-8 Autocannon": ["down", "left", "down", "up", "up", "right"],
        "MG-206 Heavy Machine Gun": ["down", "left", "up", "down", "down"],
        "RL-77 Airburst Rocket Launcher": ["down", "up", "up", "left", "right"],
        "MLS-4X Commando": ["down", "left", "up", "down", "right"],
        "RS-422 Railgun": ["down", "right", "down", "up", "left", "right"],
        "FAF-14 Spear": ["down", "down", "up", "down", "down"],
        "StA-X3 W.A.S.P. Launcher": ["down", "down", "up", "down", "right"],
    },
    "Orbital Cannons": {
        "Orbital Gatling Barrage": ["right", "down", "left", "up", "up"],
        "Orbital Airburst Strike": ["right", "right", "right"],
        "Orbital 120MM HE Barrage": ["right", "right", "down", "left", "right", "down"],
        "Orbital 380MM HE Barrage": ["right", "down", "up", "up", "left", "down", "down"],
        "Orbital Walking Barrage": ["right", "down", "right", "down", "right", "down"],
        "Orbital Laser": ["right", "down", "up", "right", "down"],
        "Orbital Napalm Barrage": ["right", "right", "down", "left", "right", "up"],
        "Orbital Railcannon Strike": ["right", "up", "down", "down", "right"],
    },
    "Hangar": {
        "Eagle Strafing Run": ["up", "right", "right"],
        "Eagle Airstrike": ["up", "right", "down", "right"],
        "Eagle Cluster Bomb": ["up", "right", "down", "down", "right"],
        "Eagle Napalm Airstrike": ["up", "right", "down", "up"],
        "LIFT-850 Jump Pack": ["down", "up", "up", "down", "up"],
        "Eagle Smoke Strike": ["up", "right", "up", "down"],
        "Eagle 110MM Rocket Pods": ["up", "right", "up", "left"],
        "Eagle 500kg Bomb": ["up", "right", "down", "down", "down"],
        "M-102 Fast Recon Vehicle": ["left", "down", "right", "down", "right", "down", "up"],
        "TD-220 Bastion": ["left", "down", "right", "down", "left", "down", "up", "down", "up"],
    },
    "Bridge": {
        "Orbital Precision Strike": ["right", "right", "up"],
        "Orbital Gas Strike": ["right", "right", "down", "right"],
        "Orbital EMS Strike": ["right", "right", "left", "down"],
        "Orbital Smoke Strike": ["right", "right", "down", "up"],
        "E/MG-101 HMG Emplacement": ["down", "up", "left", "right", "right", "left"],
        "FX-12 Shield Generator Relay": ["down", "down", "left", "right", "left", "right"],
        "A/ARC-3 Tesla Tower": ["down", "up", "right", "up", "left", "right"],
        "E/GL-21 Grenadier Battlement": ["down", "right", "down", "left", "right"],
    },
    "Engineering Bay": {
        "MD-6 Anti-Personnel Minefield": ["down", "left", "up", "right"],
        "B-1 Supply Pack": ["down", "left", "down", "up", "up", "down"],
        "GL-21 Grenade Launcher": ["down", "left", "up", "left", "down"],
        "LAS-98 Laser Cannon": ["down", "left", "down", "up", "left"],
        "MD-I4 Incendiary Mines": ["down", "left", "left", "down"],
        "AX/LAS-5 \"Guard Dog\" Rover": ["down", "up", "left", "up", "right", "right"],
        "SH-20 Ballistic Shield Backpack": ["down", "left", "down", "down", "up", "left"],
        "ARC-3 Arc Thrower": ["down", "right", "down", "up", "left", "left"],
        "MD-17 Anti-Tank Mines": ["down", "left", "up", "up"],
        "LAS-99 Quasar Cannon": ["down", "down", "up", "left", "right"],
        "SH-32 Shield Generator Pack": ["down", "up", "left", "right", "left", "right"],
        "MD-8 Gas Mines": ["down", "left", "left", "right"],
    },
    "Robotics Workshop": {
        "A/MG-43 Machine Gun Sentry": ["down", "up", "right", "right", "up"],
        "A/G-16 Gatling Sentry": ["down", "up", "right", "left"],
        "A/M-12 Mortar Sentry": ["down", "up", "right", "right", "down"],
        "AX/AR-23 \"Guard Dog\"": ["down", "up", "left", "up", "right", "down"],
        "A/AC-8 Autocannon Sentry": ["down", "up", "right", "up", "left", "up"],
        "A/MLS-4X Rocket Sentry": ["down", "up", "right", "right", "left"],
        "A/M-23 EMS Mortar Sentry": ["down", "up", "right", "down", "right"],
        "EXO-45 Patriot Exosuit": ["left", "down", "right", "up", "left", "down", "down"],
        "EXO-49 Emancipator Exosuit": ["left", "down", "right", "up", "left", "down", "up"],
    },
    "Warbonds": {
        "TX-41 Sterilizer": ["down", "left", "up", "down", "left"],
        "AX/TX-13 \"Guard Dog\" Dog Breath": ["down", "up", "left", "up", "right", "up"],
        "SH-51 Directional Shield": ["down", "up", "left", "right", "up", "up"],
        "E/AT-12 Anti-Tank Emplacement": ["down", "up", "left", "right", "right", "right"],
        "A/FLAM-40 Flame Sentry": ["down", "up", "right", "down", "up", "up"],
        "B-100 Portable Hellbomb": ["down", "right", "up", "up", "up"],
        "LIFT-860 Hover Pack": ["down", "up", "up", "down", "left", "right"],
        "CQC-1 One True Flag": ["down", "left", "right", "right", "up"],
        "GL-52 De-Escalator": ["down", "right", "up", "left", "right"],
        "AX/ARC-3 \"Guard Dog\" K-9": ["down", "up", "left", "up", "right", "left"],
        "PLAS-45 Epoch": ["down", "left", "up", "left", "right"],
        "A/LAS-98 Laser Sentry": ["down", "up", "right", "down", "up", "right"],
        "LIFT-182 Warp Pack": ["down", "left", "right", "down", "left", "right"],
        "S-11 Speargun": ["down", "right", "down", "left", "up", "right"],
        "EAT-700 Expendable Napalm": ["down", "down", "left", "up", "left"],
        "MS-11 Solo Silo": ["down", "up", "right", "down", "down"],
        "M-1000 Maxigun": ["down", "left", "right", "down", "up", "up"],
        "CQC-9 Defoliation Tool": ["down", "left", "right", "right", "down"],
        "AX/FLAM-75 \"Guard Dog\" Hot Dog": ["down", "up", "left", "up", "left", "left"],
        "B/MD C4 Pack": ["down", "right", "up", "up", "right", "up"],
        "CQC-20 Breaching Hammer": ["down", "left", "right", "left", "up"],
        "EAT-411 Leveller": ["down", "down", "left", "up", "down"],
        "GL-28 Belt-Fed Grenade Launcher": ["down", "left", "up", "left", "up", "up"],
    },
    "Mission Specific": {
        "Reinforce": ["up", "down", "right", "left", "up"],
        "SOS Beacon": ["up", "down", "right", "up"],
        "Resupply": ["down", "down", "up", "right"],
        "Eagle Rearm": ["up", "up", "left", "up", "right"],
        "SSSD Delivery": ["down", "down", "down", "up", "up"],
        "Prospecting Drill": ["down", "down", "left", "right", "down", "down"],
        "Super Earth Flag": ["down", "up", "down", "up"],
        "Hellbomb": ["down", "up", "left", "down", "up", "right", "down", "up"],
        "Upload Data": ["left", "right", "up", "up", "up"],
        "Seismic Probe": ["up", "up", "left", "right", "down", "down"],
        "Dark Fluid Vessel": ["up", "left", "right", "down", "up", "up"],
        "Tectonic Drill": ["up", "down", "up", "down", "up", "down"],
        "Hive Breaker Drill": ["left", "up", "down", "right", "down", "down"],
        "Cargo Container": ["up", "up", "down", "down", "right", "down"],
        "Orbital Illumination Flare": ["right", "right", "left", "left"],
        "SEAF Artillery": ["right", "up", "up", "down"],
        "Call In Super Destroyer": ["up", "up", "down", "down", "left", "right", "left", "right"],
    },
}

STRATAGEMS = {}
for department, stratagems in STRATAGEMS_BY_DEPARTMENT.items():
    STRATAGEMS.update(stratagems)
